Repository padaiyal/.github, pull requests merged in 2022-01, with the labels that each got.

#13 Only retain actions for maven end to end build and publishing package.
  workflow-templates/maven_linting_check.properties.json
  workflow-templates/maven_linting_check.yml
  workflow-templates/maven_static_code_analysis_check.properties.json
  workflow-templates/maven_static_code_analysis_check.yml
  workflow-templates/maven_tests_and_code_coverage_check.properties.json
  workflow-templates/maven_tests_and_code_coverage_check.yml
Labels: enhancement, continuous integration, continous deployment

#14 Add github actions for linting and unit testing for Python
  README.md
  workflow-templates/python_build.json
  workflow-templates/python_build.yml
Labels: continuous integration

#16 Rename python_build.json to python_build.properties.json
  workflow-templates/python_build.properties.json
Labels: bug, continuous integration
